<a href="https://colab.research.google.com/github/KevinCandra9999/colab-3/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [78]:
import pandas as pd
from urllib.request import urlopen
pd.__version__

'1.5.3'

### Mengenal dan membuat DataFrame

In [3]:
pd.read_csv('https://thinkjubilee.com/sekolah.csv')

                Provinsi     SD    SMP    SMA     PT
0                   ACEH  99.85  98.09  82.15  34.28
1         SUMATERA UTARA  99.49  96.60  76.76  26.80
2         SUMATERA BARAT  99.50  96.29  82.86  35.45
3                   RIAU  98.98  94.73  76.52  27.28
4                  JAMBI  99.59  95.89  71.54  24.12
5       SUMATERA SELATAN  99.63  94.01  69.05  19.17
6               BENGKULU  99.80  97.20  79.07  29.90
7                LAMPUNG  99.78  94.76  70.03  20.96
8   KEP. BANGKA BELITUNG  99.64  92.41  66.99  14.99
9              KEP. RIAU  99.32  99.08  82.80  19.13
10           DKI JAKARTA  99.67  97.64  71.50  24.60
11            JAWA BARAT  99.51  93.77  66.62  21.50
12           JAWA TENGAH  99.62  95.48  68.48  22.13
13         DI YOGYAKARTA  99.87  99.63  87.61  51.33
14            JAWA TIMUR  99.57  96.77  71.51  23.34
15                BANTEN  99.31  95.67  67.77  21.33
16                  BALI  99.44  97.72  82.16  26.56
17   NUSA TENGGARA BARAT  99.43  97.69  76.61  28.52
18   NUSA TENGGARA TIMUR  98.27  94.76  74.65  27.80
19      KALIMANTAN BARAT  98.44  92.51  67.53  25.80
20     KALIMANTAN TENGAH  99.50  93.37  66.62  24.15
21    KALIMANTAN SELATAN  99.55  92.33  68.30  23.53
22      KALIMANTAN TIMUR  99.67  98.79  81.32  30.04
23      KALIMANTAN UTARA  98.34  96.04  75.12  20.72
24        SULAWESI UTARA  99.37  94.91  73.04  24.22
25       SULAWESI TENGAH  98.15  92.41  74.87  26.31
26      SULAWESI SELATAN  99.16  93.09  70.60  32.16
27     SULAWESI TENGGARA  99.32  94.08  72.94  30.03
28             GORONTALO  98.76  91.23  69.86  29.21
29        SULAWESI BARAT  98.10  89.88  68.03  23.49
30                MALUKU  99.72  96.86  79.08  38.20
31          MALUKU UTARA  99.19  97.24  76.06  32.10
32           PAPUA BARAT  97.27  96.92  80.60  31.92
33                 PAPUA  81.80  79.09  63.35  24.57

In [4]:
pendidikan = pd.read_csv('https://thinkjubilee.com/sekolah.csv')

In [5]:
type(pendidikan)

pandas.core.frame.DataFrame

### Drop pada kolom

In [6]:
nama = ['Joni','Jono','Jana','Jini','Junu']
usia = [20,22,24,26,28]
menikah = [False,True,True,False,True]

In [7]:
df = pd.DataFrame ({'nama' : nama, 'usia' : usia, 'menikah' : menikah})

In [8]:
df

   nama  usia  menikah
0  Joni    20    False
1  Jono    22     True
2  Jana    24     True
3  Jini    26    False
4  Junu    28     True

In [9]:
df.drop('nama',axis=1)

   usia  menikah
0    20    False
1    22     True
2    24     True
3    26    False
4    28     True

### sample pada Data (menampilkan data secara acak)

In [10]:
df.sample(3)

   nama  usia  menikah
3  Jini    26    False
1  Jono    22     True
0  Joni    20    False

In [11]:
df.axes

[RangeIndex(start=0, stop=5, step=1),
 Index(['nama', 'usia', 'menikah'], dtype='object')]

In [12]:
df.axes[0]

RangeIndex(start=0, stop=5, step=1)

In [13]:
df.axes[1]

Index(['nama', 'usia', 'menikah'], dtype='object')

In [14]:
df.axes[1][2]

'menikah'

In [15]:
df.index[2]

2

In [16]:
df.columns[2]

'menikah'

In [17]:
df

   nama  usia  menikah
0  Joni    20    False
1  Jono    22     True
2  Jana    24     True
3  Jini    26    False
4  Junu    28     True

In [18]:
df.loc[2]

nama       Jana
usia         24
menikah    True
Name: 2, dtype: object

In [19]:
pd.read_csv('https://thinkjubilee.com/sekolah.csv')

                Provinsi     SD    SMP    SMA     PT
0                   ACEH  99.85  98.09  82.15  34.28
1         SUMATERA UTARA  99.49  96.60  76.76  26.80
2         SUMATERA BARAT  99.50  96.29  82.86  35.45
3                   RIAU  98.98  94.73  76.52  27.28
4                  JAMBI  99.59  95.89  71.54  24.12
5       SUMATERA SELATAN  99.63  94.01  69.05  19.17
6               BENGKULU  99.80  97.20  79.07  29.90
7                LAMPUNG  99.78  94.76  70.03  20.96
8   KEP. BANGKA BELITUNG  99.64  92.41  66.99  14.99
9              KEP. RIAU  99.32  99.08  82.80  19.13
10           DKI JAKARTA  99.67  97.64  71.50  24.60
11            JAWA BARAT  99.51  93.77  66.62  21.50
12           JAWA TENGAH  99.62  95.48  68.48  22.13
13         DI YOGYAKARTA  99.87  99.63  87.61  51.33
14            JAWA TIMUR  99.57  96.77  71.51  23.34
15                BANTEN  99.31  95.67  67.77  21.33
16                  BALI  99.44  97.72  82.16  26.56
17   NUSA TENGGARA BARAT  99.43  97.69  76.61  28.52
18   NUSA TENGGARA TIMUR  98.27  94.76  74.65  27.80
19      KALIMANTAN BARAT  98.44  92.51  67.53  25.80
20     KALIMANTAN TENGAH  99.50  93.37  66.62  24.15
21    KALIMANTAN SELATAN  99.55  92.33  68.30  23.53
22      KALIMANTAN TIMUR  99.67  98.79  81.32  30.04
23      KALIMANTAN UTARA  98.34  96.04  75.12  20.72
24        SULAWESI UTARA  99.37  94.91  73.04  24.22
25       SULAWESI TENGAH  98.15  92.41  74.87  26.31
26      SULAWESI SELATAN  99.16  93.09  70.60  32.16
27     SULAWESI TENGGARA  99.32  94.08  72.94  30.03
28             GORONTALO  98.76  91.23  69.86  29.21
29        SULAWESI BARAT  98.10  89.88  68.03  23.49
30                MALUKU  99.72  96.86  79.08  38.20
31          MALUKU UTARA  99.19  97.24  76.06  32.10
32           PAPUA BARAT  97.27  96.92  80.60  31.92
33                 PAPUA  81.80  79.09  63.35  24.57

In [20]:
DataProvinsi = pd.read_csv('https://thinkjubilee.com/sekolah.csv', index_col='Provinsi')

In [21]:
DataProvinsi.loc['JAMBI']

SD     99.59
SMP    95.89
SMA    71.54
PT     24.12
Name: JAMBI, dtype: float64

In [22]:
DataProvinsi.loc['DKI JAKARTA']['SD']

99.67

In [23]:
DataProvinsi.loc['DKI JAKARTA':'DI YOGYAKARTA']

                  SD    SMP    SMA     PT
Provinsi
DKI JAKARTA    99.67  97.64  71.50  24.60
JAWA BARAT     99.51  93.77  66.62  21.50
JAWA TENGAH    99.62  95.48  68.48  22.13
DI YOGYAKARTA  99.87  99.63  87.61  51.33

In [24]:
DataProvinsi.loc[['DKI JAKARTA','DI YOGYAKARTA'],['SD','SMP']]

                  SD    SMP
Provinsi
DKI JAKARTA    99.67  97.64
DI YOGYAKARTA  99.87  99.63

### Bekerja dengan Dataset

In [25]:
data_url = 'http://thinkjubilee.com/bola.csv'
pemainbola = pd.read_csv(data_url)

In [26]:
pemainbola

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1
464,Diafra Sakho,West+Ham,27,CF,1,10.0,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

### indexing dengan boolean mask

In [27]:
pemainbola.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [28]:
pemainbola.market_value

0      65.0
1      50.0
2       7.0
3      20.0
4      22.0
       ...
460     5.0
461     7.0
462     4.5
463     1.0
464    10.0
Name: market_value, Length: 465, dtype: float64

In [29]:
pemainbola.market_value	>= 60

0       True
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Name: market_value, Length: 465, dtype: bool

In [30]:
pemainbola[pemainbola.market_value > 50]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
96,Eden Hazard,Chelsea,26,LW,1,75.0,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.0,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Manchester+City,29,CF,1,65.0,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
267,Paul Pogba,Manchester+United,24,CM,2,75.0,7435,8.0,19.50%,115,2,France,0,2,12,1,1
381,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0

In [31]:
pemainbola[pemainbola.market_value	== 65].shape

(3, 17)

In [32]:
pemainbola.nationality.unique()

array(['Chile', 'Germany', 'Czech Republic', 'England', 'France', 'Spain',
       'Nigeria', 'Switzerland', 'Wales', 'Brazil', 'Egypt', 'Argentina',
       'Colombia', 'Bosnia', 'Norway', 'Poland', 'Scotland', 'Congo DR',
       'Ireland', 'Netherlands', 'Australia', "Cote d'Ivoire", 'Finland',
       'Cameroon', 'Austria', 'Israel', 'Northern Ireland', 'Canada',
       'Belgium', 'Iceland', 'Serbia', 'Portugal', 'Ghana', 'South Korea',
       'Mali', 'Senegal', 'Curacao', 'Denmark', 'Slovenia',
       'Trinidad and Tobago', 'Bermuda', 'Benin', 'Algeria', 'Jamaica',
       'Japan', 'Tunisia', 'Croatia', 'Estonia', 'Ecuador', 'Armenia',
       'Italy', 'Sweden', 'United States', 'Morocco', 'The Gambia',
       'Kenya', 'Greece', 'Uruguay', 'Romania', 'Venezuela',
       'New Zealand'], dtype=object)

In [33]:
pemainbola.nationality.unique().size

61

In [34]:
pemainbola.nationality.isin(['England', 'South Korea', 'Italy'])

0      False
1      False
2      False
3       True
4      False
       ...
460    False
461    False
462     True
463     True
464    False
Name: nationality, Length: 465, dtype: bool

In [35]:
pemainbola[pemainbola.nationality.isin(['England', 'South Korea', 'Italy'])]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
12,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
13,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
14,Jack Wilshere,Arsenal,25,CM,2,18.0,1759,5.5,0.00%,61,1,England,0,3,1,1,0
18,Kieran Gibbs,Arsenal,27,LB,3,10.0,489,5.0,0.50%,45,1,England,0,3,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Andy Carroll,West+Ham,28,CF,1,10.0,1212,6.0,0.40%,69,1,England,0,4,20,0,0
455,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
458,Angelo Ogbonna,West+Ham,29,CB,3,9.0,247,4.5,1.10%,45,2,Italy,0,4,20,0,0
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1

### Method Between

In [36]:
pemainbola[pemainbola.market_value.between(65,75)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
96,Eden Hazard,Chelsea,26,LW,1,75.0,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.0,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Manchester+City,29,CF,1,65.0,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
267,Paul Pogba,Manchester+United,24,CM,2,75.0,7435,8.0,19.50%,115,2,France,0,2,12,1,1

In [37]:
pemainbola[pemainbola.market_value.between(65,75, inclusive=False)]

<ipython-input-37-47f6d8980ea2>:1: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  pemainbola[pemainbola.market_value.between(65,75, inclusive=False)]

Empty DataFrame
Columns: [name, club, age, position, position_cat, market_value, page_views, fpl_value, fpl_sel, fpl_points, region, nationality, new_foreign, age_cat, club_id, big_club, new_signing]
Index: []

### method dan comparison operator

In [38]:
pemainbola[pemainbola.age >= 25].shape

(335, 17)

In [39]:
pemainbola[pemainbola.age.le(25)].shape

(172, 17)

In [40]:
pemainbola[pemainbola.age.lt(25)].shape

(130, 17)

In [41]:
pemainbola[pemainbola.age.gt(25)].shape

(293, 17)

In [42]:
pemainbola[pemainbola.age.ge(25)].shape

(335, 17)

In [43]:
pemainbola[pemainbola.age.eq(25)].shape

(42, 17)

### MEngkombinasi kondisi

In [44]:
pemainbola[(pemainbola.market_value.gt(30)) &
            (pemainbola.nationality == 'England')]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
246,Raheem Sterling,Manchester+City,22,LW,1,45.0,2074,8.0,3.80%,149,1,England,0,2,11,1,0
256,John Stones,Manchester+City,23,CB,3,35.0,1078,5.5,2.30%,59,1,England,0,2,11,1,1
380,Dele Alli,Tottenham,21,CM,2,45.0,4626,9.5,38.60%,225,1,England,0,1,17,1,0
381,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0

In [45]:
pemainbola[(pemainbola.age.lt(30)) &
            (pemainbola.club == 'Arsenal') &
             (pemainbola.market_value.gt(30))]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
10,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
11,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
15,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
31,Alexandre Lacazette,Arsenal,26,CF,1,40.0,1183,10.5,26.50%,0,2,France,1,3,1,1,0

### Memasukan kondisi kedalam variabel

In [46]:
usia = pemainbola.age.lt(30)
klub = pemainbola.club == 'Arsenal'
market = pemainbola.market_value.gt(30)
pemainbola[(usia) &
          (klub) &
          (market)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
10,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
11,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
15,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
31,Alexandre Lacazette,Arsenal,26,CF,1,40.0,1183,10.5,26.50%,0,2,France,1,3,1,1,0

In [47]:
usia = pemainbola.age.lt(30)
klub = pemainbola.club == 'Arsenal'
market = pemainbola.market_value.gt(30)
pemainbola[(usia) |
          (klub) |
          (market)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1
464,Diafra Sakho,West+Ham,27,CF,1,10.0,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

### 2d indexing

In [48]:
usia = pemainbola.age.lt(30)
klub = pemainbola.club == 'Arsenal'
market = pemainbola.market_value.gt(30)
pemainbola.loc[(usia) & (klub) & (market), ['name','age','club','market_value','nationality']]

                   name  age     club  market_value  nationality
0        Alexis Sanchez   28  Arsenal          65.0        Chile
1            Mesut Ozil   28  Arsenal          50.0      Germany
10         Granit Xhaka   24  Arsenal          35.0  Switzerland
11         Granit Xhaka   24  Arsenal          35.0  Switzerland
15         Aaron Ramsey   26  Arsenal          35.0        Wales
31  Alexandre Lacazette   26  Arsenal          40.0       France

### melakukan Sorting

In [49]:
pemainbola.sort_values(by='age', ascending=False)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
136,Julian Speroni,Crystal+Palace,38,GK,4,0.25,188,4.0,2.00%,0,3,Argentina,0,6,6,0,0
35,Artur Boruc,Bournemouth,37,GK,4,1.00,436,4.5,6.90%,120,2,Poland,0,6,2,0,0
424,Gareth McAuley,West+Brom,37,CB,3,1.00,458,5.0,11.80%,131,2,Northern Ireland,0,6,19,0,0
61,Bruno,Brighton+and+Hove,36,RB,1,0.50,215,4.5,0.40%,0,3,Argentina,0,6,3,0,0
402,Heurelho Gomes,Watford,36,GK,4,1.00,439,4.5,2.20%,113,3,Brazil,0,6,18,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,Ademola Lookman,Everton,19,LW,1,5.00,1387,5.5,0.30%,16,1,England,0,1,7,0,0
439,Jonathan Leko,West+Brom,18,RW,1,1.50,169,4.5,0.20%,12,1,England,0,1,19,0,0
354,Josh Tymon,Stoke+City,18,LB,3,1.00,120,4.5,0.10%,9,1,England,0,1,15,0,0
235,Trent Alexander-Arnold,Liverpool,18,RB,3,1.50,327,4.5,0.30%,15,2,England,0,1,10,1,0
237,Ben Woodburn,Liverpool,17,LW,1,1.50,1241,4.5,0.10%,5,1,Wales,0,1,10,1,0

In [50]:
usia = pemainbola.age.lt(30)
klub = pemainbola.club == 'Arsenal'
market = pemainbola.market_value.gt(30)
pemainbola.loc[(usia) & (klub) & (market), ['name','age','club','market_value','nationality']].sort_values(by='age', ascending=False)

                   name  age     club  market_value  nationality
0        Alexis Sanchez   28  Arsenal          65.0        Chile
1            Mesut Ozil   28  Arsenal          50.0      Germany
15         Aaron Ramsey   26  Arsenal          35.0        Wales
31  Alexandre Lacazette   26  Arsenal          40.0       France
10         Granit Xhaka   24  Arsenal          35.0  Switzerland
11         Granit Xhaka   24  Arsenal          35.0  Switzerland

### Mencari data dukplikat

In [51]:
pemainbola[pemainbola.duplicated()]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
11,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
13,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
23,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0

In [52]:
pemainbola[pemainbola.duplicated(subset=['club','age','nationality','market_value'], keep='first')]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
11,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
13,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
23,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
38,Adam Smith,Bournemouth,26,RB,3,5.0,200,5.0,0.90%,104,1,England,0,3,2,0,0
47,Andrew Surman,Bournemouth,30,CM,2,2.0,154,4.5,1.10%,44,1,England,0,4,2,0,0
260,Fernando,Manchester+City,32,DM,2,18.0,338,4.5,0.40%,18,3,Brazil,0,5,11,1,0
302,Jack Colback,Newcastle+United,27,DM,2,5.0,181,4.5,1.10%,0,1,England,0,3,13,0,0

### mengguranakan drop duplicated

In [53]:
pemainbola[pemainbola.duplicated()]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
11,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
13,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
23,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0

In [54]:
pemainbola.market_value.mean()

11.125649350649349

In [55]:
pemainbola.drop_duplicates(keep='first').market_value.mean()

11.026252723311545

### Mengatasi NaN

In [56]:
pemainbola[pemainbola.isna().values]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
30,Granit Xhaka,Arsenal,24,NaN,2,NaN,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
30,Granit Xhaka,Arsenal,24,NaN,2,NaN,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
192,Steve Mounie,Huddersfield,22,CF,1,NaN,56,6.0,0.60%,0,2,Benin,0,2,8,0,0
195,Kasper Schmeichel,Leicester+City,30,GK,4,NaN,1601,5.0,2.40%,109,2,Denmark,0,4,9,0,0

In [57]:
pemainbola.fillna({'position' : 'CF',
                   'market_value' : 11}).loc[[30,192,195]]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
30,Granit Xhaka,Arsenal,24,CF,2,11.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
192,Steve Mounie,Huddersfield,22,CF,1,11.0,56,6.0,0.60%,0,2,Benin,0,2,8,0,0
195,Kasper Schmeichel,Leicester+City,30,GK,4,11.0,1601,5.0,2.40%,109,2,Denmark,0,4,9,0,0

### menambah kolom baru

In [58]:
pemainbola ['class'] = 'A'

In [59]:
pemainbola[pemainbola.market_value > 30]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing,class
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0,A
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0,A
10,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0,A
11,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0,A
15,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0,A
31,Alexandre Lacazette,Arsenal,26,CF,1,40.0,1183,10.5,26.50%,0,2,France,1,3,1,1,0,A
96,Eden Hazard,Chelsea,26,LW,1,75.0,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0,A
97,Diego Costa,Chelsea,28,CF,1,50.0,4454,10.0,3.00%,196,2,Spain,0,4,5,1,0,A
102,Thibaut Courtois,Chelsea,25,GK,4,40.0,1260,5.5,18.50%,141,2,Belgium,0,3,5,1,0,A
104,Cesc Fabregas,Chelsea,30,CM,2,35.0,2378,7.0,7.50%,121,2,Spain,0,4,5,1,0,A
105,Willian,Chelsea,28,RW,1,32.0,1165,7.0,9.00%,114,3,Brazil,0,4,5,1,0,A
107,Nemanja Matic,Chelsea,28,DM,2,35.0,892,5.0,5.00%,105,2,Serbia,0,4,5,1,0,A
108,N%27Golo Kante,Chelsea,26,DM,2,50.0,4042,5.0,13.80%,83,2,France,0,3,5,1,1,A
217,Roberto Firmino,Liverpool,25,SS,1,38.0,2196,8.5,20.30%,180,3,Brazil,0,3,10,1,0,A
218,Philippe Coutinho,Liverpool,25,AM,1,45.0,2958,9.0,30.80%,171,3,Brazil,0,3,10,1,0,A
219,Sadio Mane,Liverpool,25,LW,1,40.0,3219,9.5,5.30%,156,4,Senegal,0,3,10,1,1,A
241,Mohamed Salah,Liverpool,25,RW,1,35.0,1117,9.0,12.40%,0,4,Egypt,1,3,10,1,0,A
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.0,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0,A
245,Sergio Aguero,Manchester+City,29,CF,1,65.0,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0,A
246,Raheem Sterling,Manchester+City,22,LW,1,45.0,2074,8.0,3.80%,149,1,England,0,2,11,1,0,A
249,Leroy Sane,Manchester+City,21,LW,1,35.0,2302,8.5,8.80%,105,2,Germany,0,1,11,1,1,A
256,John Stones,Manchester+City,23,CB,3,35.0,1078,5.5,2.30%,59,1,England,0,2,11,1,1,A
263,Bernardo Silva,Manchester+City,22,RW,1,40.0,1098,8.0,4.60%,0,2,Portugal,1,2,11,1,0,A
264,Romelu Lukaku,Manchester+United,24,CF,1,50.0,3727,11.5,45.00%,221,2,Belgium,0,2,12,1,0,A
265,David de Gea,Manchester+United,26,GK,4,40.0,2126,5.5,26.10%,136,2,Spain,0,3,12,1,0,A
267,Paul Pogba,Manchester+United,24,CM,2,75.0,7435,8.0,19.50%,115,2,France,0,2,12,1,1,A
275,Henrikh Mkhitaryan,Manchester+United,28,AM,1,35.0,3312,8.0,4.50%,73,4,Armenia,0,4,12,1,1,A
380,Dele Alli,Tottenham,21,CM,2,45.0,4626,9.5,38.60%,225,1,England,0,1,17,1,0,A
381,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0,A
382,Christian Eriksen,Tottenham,25,AM,1,40.0,1130,9.5,12.00%,218,2,Denmark,0,3,17,1,0,A
386,Toby Alderweireld,Tottenham,28,CB,3,35.0,756,6.0,13.30%,120,2,Belgium,0,4,17,1,0,A

In [60]:
pemainbola_kecil = pemainbola.iloc[:5, 0:3]
pemainbola_kecil

                name     club  age
0     Alexis Sanchez  Arsenal   28
1         Mesut Ozil  Arsenal   28
2          Petr Cech  Arsenal   35
3       Theo Walcott  Arsenal   28
4  Laurent Koscielny  Arsenal   31

In [61]:
nickname = pd.Series(['Alex','Mesut','Petr','Theo','Laurent'])
pemainbola_kecil.insert (1, 'nickname', nickname)

In [62]:
pemainbola_kecil.drop(columns=['nickname'], inplace = True)

In [63]:
pemainbola_kecil

                name     club  age
0     Alexis Sanchez  Arsenal   28
1         Mesut Ozil  Arsenal   28
2          Petr Cech  Arsenal   35
3       Theo Walcott  Arsenal   28
4  Laurent Koscielny  Arsenal   31

In [64]:
pemainbola_kecil.assign(goals=[15, 20, 0, 11, 14])

                name     club  age  goals
0     Alexis Sanchez  Arsenal   28     15
1         Mesut Ozil  Arsenal   28     20
2          Petr Cech  Arsenal   35      0
3       Theo Walcott  Arsenal   28     11
4  Laurent Koscielny  Arsenal   31     14

### Menambahkan data baru

In [65]:
pemainbola_kecil

                name     club  age
0     Alexis Sanchez  Arsenal   28
1         Mesut Ozil  Arsenal   28
2          Petr Cech  Arsenal   35
3       Theo Walcott  Arsenal   28
4  Laurent Koscielny  Arsenal   31

In [66]:
namajoni = pd.Series({
    'name' : 'Jonio Ronaldo',
    'nickname' : 'Joni',
    'club' : 'Arsenal',
    'age' : 20},
    name = 5)

In [67]:
pemainbola_kecil.append(namajoni)

<ipython-input-67-a7e391474cc9>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pemainbola_kecil.append(namajoni)

                name     club  age nickname
0     Alexis Sanchez  Arsenal   28      NaN
1         Mesut Ozil  Arsenal   28      NaN
2          Petr Cech  Arsenal   35      NaN
3       Theo Walcott  Arsenal   28      NaN
4  Laurent Koscielny  Arsenal   31      NaN
5      Jonio Ronaldo  Arsenal   20     Joni

In [68]:
namapemainbaru = pd.DataFrame({
    'name' : ["Toni Messi", "edi Neymar"],
    'nickname' : ['Toni','Edi'],
    'club' : ['Chelsea','Barcelona'],
    'age' : [21,22]},
      index=[6,7])

In [69]:
pemainbola_kecil.append(namapemainbaru)

<ipython-input-69-5309d6a200e0>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pemainbola_kecil.append(namapemainbaru)

                name       club  age nickname
0     Alexis Sanchez    Arsenal   28      NaN
1         Mesut Ozil    Arsenal   28      NaN
2          Petr Cech    Arsenal   35      NaN
3       Theo Walcott    Arsenal   28      NaN
4  Laurent Koscielny    Arsenal   31      NaN
6         Toni Messi    Chelsea   21     Toni
7         edi Neymar  Barcelona   22      Edi

### BEKERJA DENGAN BEBRAPA DATAFRAMES

In [114]:
engineering = 'http://thinkjubilee.com/data/engineering.csv'
state = 'http://thinkjubilee.com/data/state.csv'
ivies = 'http://thinkjubilee.com/data/ivies.csv'
liberalarts = 'http://thinkjubilee.com/data/liberalarts.csv'
wilayah = 'http://thinkjubilee.com/data/regions.csv'

In [81]:
en = pd.read_csv(engineering)

In [92]:
en.sort_values(by=['Starting Median Salary'], ascending=False)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
6,Carnegie Mellon University (CMU),Engineering,"$61,800.00","$111,000.00"
7,Rensselaer Polytechnic Institute (RPI),Engineering,"$61,100.00","$110,000.00"
5,Worcester Polytechnic Institute (WPI),Engineering,"$61,000.00","$114,000.00"
10,Stevens Institute of Technology,Engineering,"$60,600.00","$105,000.00"
8,Georgia Institute of Technology,Engineering,"$58,300.00","$106,000.00"
9,Colorado School of Mines,Engineering,"$58,100.00","$106,000.00"
11,Illinois Institute of Technology (IIT),Engineering,"$56,000.00","$97,800.00"
14,South Dakota School of Mines & Technology,Engineering,"$55,800.00","$93,400.00"
13,Virginia Polytechnic Institute and State Unive...,Engineering,"$53,500.00","$95,400.00"
12,Wentworth Institute of Technology,Engineering,"$53,000.00","$96,700.00"
17,Embry-Riddle Aeronautical University (ERAU),Engineering,"$52,700.00","$80,700.00"
15,New Mexico Institute of Mining and Technology ...,Engineering,"$51,000.00","$93,400.00"
16,Rochester Institute of Technology (RIT),Engineering,"$48,900.00","$84,600.00"
18,Tennessee Technological University,Engineering,"$46,200.00","$80,000.00"

In [82]:
st = pd.read_csv(state)

In [93]:
st.sort_values(by=['Starting Median Salary'], ascending=False)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,"University of California, Berkeley",State,"$59,900.00","$112,000.00"
2,Cal Poly San Luis Obispo,State,"$57,200.00","$101,000.00"
11,University of Missouri - Rolla (UMR),State,"$57,100.00","$95,800.00"
10,Binghamton University,State,"$53,600.00","$95,900.00"
12,San Jose State University (SJSU),State,"$53,500.00","$95,600.00"
...,...,...,...,...
156,Western Carolina University,State,"$36,900.00","$66,600.00"
148,Missouri State University (MSU),State,"$36,100.00","$69,500.00"
168,University of Wisconsin (UW) - Green Bay,State,"$35,800.00","$60,600.00"
174,Black Hills State University,State,"$35,300.00","$43,900.00"
169,Morehead State University,State,"$34,800.00","$60,600.00"

In [83]:
art = pd.read_csv(liberalarts)

In [96]:
art.sort_values(by=['Starting Median Salary'], ascending=False)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
2,Amherst College,Liberal Arts,"$54,500.00","$107,000.00"
0,Bucknell University,Liberal Arts,"$54,100.00","$110,000.00"
3,Lafayette College,Liberal Arts,"$53,900.00","$107,000.00"
7,Washington and Lee University,Liberal Arts,"$53,600.00","$104,000.00"
1,Colgate University,Liberal Arts,"$52,800.00","$108,000.00"
6,Occidental College,Liberal Arts,"$51,900.00","$105,000.00"
11,Williams College,Liberal Arts,"$51,700.00","$102,000.00"
5,College of the Holy Cross,Liberal Arts,"$50,200.00","$106,000.00"
8,Swarthmore College,Liberal Arts,"$49,700.00","$104,000.00"
27,Hamilton College,Liberal Arts,"$49,200.00","$83,700.00"
20,Franklin and Marshall College,Liberal Arts,"$49,100.00","$92,800.00"
12,Pomona College,Liberal Arts,"$48,600.00","$101,000.00"
16,University of Richmond,Liberal Arts,"$48,600.00","$94,600.00"
4,Bowdoin College,Liberal Arts,"$48,100.00","$107,000.00"
18,Middlebury College,Liberal Arts,"$47,700.00","$94,200.00"
10,Carleton College,Liberal Arts,"$47,500.00","$103,000.00"
14,Bates College,Liberal Arts,"$47,300.00","$96,500.00"
15,Union College,Liberal Arts,"$47,200.00","$95,800.00"
32,University of Puget Sound,Liberal Arts,"$46,600.00","$81,500.00"
13,"Wesleyan University (Middletown, Connecticut)",Liberal Arts,"$46,500.00","$97,900.00"
23,Colby College,Liberal Arts,"$46,400.00","$85,800.00"
9,Davidson College,Liberal Arts,"$46,100.00","$104,000.00"
17,Vassar College,Liberal Arts,"$46,000.00","$94,600.00"
25,Siena College,Liberal Arts,"$45,500.00","$85,200.00"
22,St. Olaf College,Liberal Arts,"$45,300.00","$86,200.00"
24,Gettysburg College,Liberal Arts,"$44,700.00","$85,800.00"
35,Gustavus Adolphus College,Liberal Arts,"$44,500.00","$80,600.00"
26,Smith College,Liberal Arts,"$44,000.00","$83,900.00"
36,Whitman College,Liberal Arts,"$43,500.00","$80,100.00"
31,Oberlin College,Liberal Arts,"$43,400.00","$81,600.00"
29,Wellesley College,Liberal Arts,"$42,800.00","$83,500.00"
28,Randolph-Macon College,Liberal Arts,"$42,600.00","$83,600.00"
40,Grinnell College,Liberal Arts,"$42,600.00","$76,600.00"
42,Moravian College,Liberal Arts,"$42,500.00","$74,400.00"
19,Mount Holyoke College,Liberal Arts,"$42,400.00","$94,100.00"
37,Ursinus College,Liberal Arts,"$42,100.00","$80,000.00"
30,Denison University,Liberal Arts,"$42,000.00","$83,500.00"
44,Fort Lewis College,Liberal Arts,"$42,000.00","$69,800.00"
38,Juniata College,Liberal Arts,"$41,800.00","$78,900.00"
41,Skidmore College,Liberal Arts,"$41,600.00","$74,600.00"
45,Thomas Aquinas College,Liberal Arts,"$41,500.00","$67,500.00"
21,DePauw University,Liberal Arts,"$41,400.00","$88,300.00"
34,Reed College,Liberal Arts,"$40,500.00","$81,100.00"
46,Evergreen State College,Liberal Arts,"$39,500.00","$63,900.00"
39,Wittenberg University,Liberal Arts,"$39,200.00","$78,200.00"
43,Lewis & Clark College,Liberal Arts,"$38,900.00","$72,600.00"
33,Colorado College (CC),Liberal Arts,"$38,500.00","$81,400.00"

### Concatenating DataFrames

In [84]:
pd.concat([en, st])

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
...,...,...,...,...
170,Austin Peay State University,State,"$37,700.00","$59,200.00"
171,Pittsburg State University,State,"$40,400.00","$58,200.00"
172,Southern Utah University,State,"$41,900.00","$56,500.00"
173,Montana State University - Billings,State,"$37,900.00","$50,600.00"
174,Black Hills State University,State,"$35,300.00","$43,900.00"

In [85]:
school = [en, st, art]

In [87]:
pd.concat(school)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
...,...,...,...,...
42,Moravian College,Liberal Arts,"$42,500.00","$74,400.00"
43,Lewis & Clark College,Liberal Arts,"$38,900.00","$72,600.00"
44,Fort Lewis College,Liberal Arts,"$42,000.00","$69,800.00"
45,Thomas Aquinas College,Liberal Arts,"$41,500.00","$67,500.00"
46,Evergreen State College,Liberal Arts,"$39,500.00","$63,900.00"

### Column Axis Concatenation

In [94]:
pd.concat((school), axis=0)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
...,...,...,...,...
42,Moravian College,Liberal Arts,"$42,500.00","$74,400.00"
43,Lewis & Clark College,Liberal Arts,"$38,900.00","$72,600.00"
44,Fort Lewis College,Liberal Arts,"$42,000.00","$69,800.00"
45,Thomas Aquinas College,Liberal Arts,"$41,500.00","$67,500.00"
46,Evergreen State College,Liberal Arts,"$39,500.00","$63,900.00"

In [97]:
pd.concat([en, art], axis=1)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00",Bucknell University,Liberal Arts,"$54,100.00","$110,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",Colgate University,Liberal Arts,"$52,800.00","$108,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",Amherst College,Liberal Arts,"$54,500.00","$107,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00",Lafayette College,Liberal Arts,"$53,900.00","$107,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00",Bowdoin College,Liberal Arts,"$48,100.00","$107,000.00"
5,Worcester Polytechnic Institute (WPI),Engineering,"$61,000.00","$114,000.00",College of the Holy Cross,Liberal Arts,"$50,200.00","$106,000.00"
6,Carnegie Mellon University (CMU),Engineering,"$61,800.00","$111,000.00",Occidental College,Liberal Arts,"$51,900.00","$105,000.00"
7,Rensselaer Polytechnic Institute (RPI),Engineering,"$61,100.00","$110,000.00",Washington and Lee University,Liberal Arts,"$53,600.00","$104,000.00"
8,Georgia Institute of Technology,Engineering,"$58,300.00","$106,000.00",Swarthmore College,Liberal Arts,"$49,700.00","$104,000.00"
9,Colorado School of Mines,Engineering,"$58,100.00","$106,000.00",Davidson College,Liberal Arts,"$46,100.00","$104,000.00"
10,Stevens Institute of Technology,Engineering,"$60,600.00","$105,000.00",Carleton College,Liberal Arts,"$47,500.00","$103,000.00"
11,Illinois Institute of Technology (IIT),Engineering,"$56,000.00","$97,800.00",Williams College,Liberal Arts,"$51,700.00","$102,000.00"
12,Wentworth Institute of Technology,Engineering,"$53,000.00","$96,700.00",Pomona College,Liberal Arts,"$48,600.00","$101,000.00"
13,Virginia Polytechnic Institute and State Unive...,Engineering,"$53,500.00","$95,400.00","Wesleyan University (Middletown, Connecticut)",Liberal Arts,"$46,500.00","$97,900.00"
14,South Dakota School of Mines & Technology,Engineering,"$55,800.00","$93,400.00",Bates College,Liberal Arts,"$47,300.00","$96,500.00"
15,New Mexico Institute of Mining and Technology ...,Engineering,"$51,000.00","$93,400.00",Union College,Liberal Arts,"$47,200.00","$95,800.00"
16,Rochester Institute of Technology (RIT),Engineering,"$48,900.00","$84,600.00",University of Richmond,Liberal Arts,"$48,600.00","$94,600.00"
17,Embry-Riddle Aeronautical University (ERAU),Engineering,"$52,700.00","$80,700.00",Vassar College,Liberal Arts,"$46,000.00","$94,600.00"
18,Tennessee Technological University,Engineering,"$46,200.00","$80,000.00",Middlebury College,Liberal Arts,"$47,700.00","$94,200.00"
19,NaN,NaN,NaN,NaN,Mount Holyoke College,Liberal Arts,"$42,400.00","$94,100.00"
20,NaN,NaN,NaN,NaN,Franklin and Marshall College,Liberal Arts,"$49,100.00","$92,800.00"
21,NaN,NaN,NaN,NaN,DePauw University,Liberal Arts,"$41,400.00","$88,300.00"
22,NaN,NaN,NaN,NaN,St. Olaf College,Liberal Arts,"$45,300.00","$86,200.00"
23,NaN,NaN,NaN,NaN,Colby College,Liberal Arts,"$46,400.00","$85,800.00"
24,NaN,NaN,NaN,NaN,Gettysburg College,Liberal Arts,"$44,700.00","$85,800.00"
25,NaN,NaN,NaN,NaN,Siena College,Liberal Arts,"$45,500.00","$85,200.00"
26,NaN,NaN,NaN,NaN,Smith College,Liberal Arts,"$44,000.00","$83,900.00"
27,NaN,NaN,NaN,NaN,Hamilton College,Liberal Arts,"$49,200.00","$83,700.00"
28,NaN,NaN,NaN,NaN,Randolph-Macon College,Liberal Arts,"$42,600.00","$83,600.00"
29,NaN,NaN,NaN,NaN,Wellesley College,Liberal Arts,"$42,800.00","$83,500.00"
30,NaN,NaN,NaN,NaN,Denison University,Liberal Arts,"$42,000.00","$83,500.00"
31,NaN,NaN,NaN,NaN,Oberlin College,Liberal Arts,"$43,400.00","$81,600.00"
32,NaN,NaN,NaN,NaN,University of Puget Sound,Liberal Arts,"$46,600.00","$81,500.00"
33,NaN,NaN,NaN,NaN,Colorado College (CC),Liberal Arts,"$38,500.00","$81,400.00"
34,NaN,NaN,NaN,NaN,Reed College,Liberal Arts,"$40,500.00","$81,100.00"
35,NaN,NaN,NaN,NaN,Gustavus Adolphus College,Liberal Arts,"$44,500.00","$80,600.00"
36,NaN,NaN,NaN,NaN,Whitman College,Liberal Arts,"$43,500.00","$80,100.00"
37,NaN,NaN,NaN,NaN,Ursinus College,Liberal Arts,"$42,100.00","$80,000.00"
38,NaN,NaN,NaN,NaN,Juniata College,Liberal Arts,"$41,800.00","$78,900.00"
39,NaN,NaN,NaN,NaN,Wittenberg University,Liberal Arts,"$39,200.00","$78,200.00"
40,NaN,NaN,NaN,NaN,Grinnell College,Liberal Arts,"$42,600.00","$76,600.00"
41,NaN,NaN,NaN,NaN,Skidmore College,Liberal Arts,"$41,600.00","$74,600.00"
42,NaN,NaN,NaN,NaN,Moravian College,Liberal Arts,"$42,500.00","$74,400.00"
43,NaN,NaN,NaN,NaN,Lewis & Clark College,Liberal Arts,"$38,900.00","$72,600.00"
44,NaN,NaN,NaN,NaN,Fort Lewis College,Liberal Arts,"$42,000.00","$69,800.00"
45,NaN,NaN,NaN,NaN,Thomas Aquinas College,Liberal Arts,"$41,500.00","$67,500.00"
46,NaN,NaN,NaN,NaN,Evergreen State College,Liberal Arts,"$39,500.00","$63,900.00"

### Outer dan Inner

In [98]:
en_copy = en.copy()

In [101]:
en_copy

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,location
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00",USA
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",USA
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",USA
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00",USA
4,Cooper Union,Engineering,"$62,200.00","$114,000.00",USA
5,Worcester Polytechnic Institute (WPI),Engineering,"$61,000.00","$114,000.00",USA
6,Carnegie Mellon University (CMU),Engineering,"$61,800.00","$111,000.00",USA
7,Rensselaer Polytechnic Institute (RPI),Engineering,"$61,100.00","$110,000.00",USA
8,Georgia Institute of Technology,Engineering,"$58,300.00","$106,000.00",USA
9,Colorado School of Mines,Engineering,"$58,100.00","$106,000.00",USA
10,Stevens Institute of Technology,Engineering,"$60,600.00","$105,000.00",USA
11,Illinois Institute of Technology (IIT),Engineering,"$56,000.00","$97,800.00",USA
12,Wentworth Institute of Technology,Engineering,"$53,000.00","$96,700.00",USA
13,Virginia Polytechnic Institute and State Unive...,Engineering,"$53,500.00","$95,400.00",USA
14,South Dakota School of Mines & Technology,Engineering,"$55,800.00","$93,400.00",USA
15,New Mexico Institute of Mining and Technology ...,Engineering,"$51,000.00","$93,400.00",USA
16,Rochester Institute of Technology (RIT),Engineering,"$48,900.00","$84,600.00",USA
17,Embry-Riddle Aeronautical University (ERAU),Engineering,"$52,700.00","$80,700.00",USA
18,Tennessee Technological University,Engineering,"$46,200.00","$80,000.00",USA

In [100]:
en_copy['location'] = 'USA'

In [105]:
pd.concat([en_copy, art], join='inner')

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
...,...,...,...,...
42,Moravian College,Liberal Arts,"$42,500.00","$74,400.00"
43,Lewis & Clark College,Liberal Arts,"$38,900.00","$72,600.00"
44,Fort Lewis College,Liberal Arts,"$42,000.00","$69,800.00"
45,Thomas Aquinas College,Liberal Arts,"$41,500.00","$67,500.00"
46,Evergreen State College,Liberal Arts,"$39,500.00","$63,900.00"

### Method Merge

In [109]:
wil = pd.read_csv(wilayah)
wil

                                      School Name        Region
0     Massachusetts Institute of Technology (MIT)  Northeastern
1        California Institute of Technology (CIT)    California
2                             Harvey Mudd College    California
3    Polytechnic University of New York, Brooklyn  Northeastern
4                                    Cooper Union  Northeastern
..                                            ...           ...
264                  Austin Peay State University      Southern
265                    Pittsburg State University    Midwestern
266                      Southern Utah University       Western
267           Montana State University - Billings       Western
268                  Black Hills State University    Midwestern

[269 rows x 2 columns]

In [111]:
sekolah = pd.concat((school),axis=0)

In [112]:
pd.merge(sekolah, wil, on='School Name')

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00",Northeastern
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",California
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",California
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00",Northeastern
4,Cooper Union,Engineering,"$62,200.00","$114,000.00",Northeastern
...,...,...,...,...,...
256,Moravian College,Liberal Arts,"$42,500.00","$74,400.00",Northeastern
257,Lewis & Clark College,Liberal Arts,"$38,900.00","$72,600.00",Western
258,Fort Lewis College,Liberal Arts,"$42,000.00","$69,800.00",Western
259,Thomas Aquinas College,Liberal Arts,"$41,500.00","$67,500.00",California
260,Evergreen State College,Liberal Arts,"$39,500.00","$63,900.00",Western

### Left dan Right Parameter

In [115]:
income = 'http://thinkjubilee.com/data/gaji.csv'
gaji = pd.read_csv(income)
gaji

,school_name,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
0,Massachusetts Institute of Technology (MIT),"$76,800.00","$99,200.00","$168,000.00","$220,000.00"
1,California Institute of Technology (CIT),NaN,"$104,000.00","$161,000.00",NaN
2,Harvey Mudd College,NaN,"$96,000.00","$180,000.00",NaN
3,"Polytechnic University of New York, Brooklyn","$66,800.00","$94,300.00","$143,000.00","$190,000.00"
4,Cooper Union,NaN,"$80,200.00","$142,000.00",NaN
...,...,...,...,...,...
264,Austin Peay State University,"$32,200.00","$40,500.00","$73,900.00","$96,200.00"
265,Pittsburg State University,"$25,600.00","$46,000.00","$84,600.00","$117,000.00"
266,Southern Utah University,"$30,700.00","$39,700.00","$78,400.00","$116,000.00"
267,Montana State University - Billings,"$22,600.00","$31,800.00","$78,500.00","$98,900.00"
268,Black Hills State University,"$27,000.00","$32,200.00","$60,900.00","$87,600.00"

In [119]:
pd.merge(sekolah, gaji, left_on='School Name', right_on='school_name').drop('school_name', axis=1)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00","$76,800.00","$99,200.00","$168,000.00","$220,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",NaN,"$104,000.00","$161,000.00",NaN
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",NaN,"$96,000.00","$180,000.00",NaN
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00","$66,800.00","$94,300.00","$143,000.00","$190,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00",NaN,"$80,200.00","$142,000.00",NaN
...,...,...,...,...,...,...,...,...
256,Moravian College,Liberal Arts,"$42,500.00","$74,400.00",NaN,"$56,700.00","$94,900.00",NaN
257,Lewis & Clark College,Liberal Arts,"$38,900.00","$72,600.00","$38,200.00","$53,400.00","$104,000.00","$140,000.00"
258,Fort Lewis College,Liberal Arts,"$42,000.00","$69,800.00",NaN,"$55,000.00","$94,000.00",NaN
259,Thomas Aquinas College,Liberal Arts,"$41,500.00","$67,500.00",NaN,"$44,600.00","$93,100.00",NaN
260,Evergreen State College,Liberal Arts,"$39,500.00","$63,900.00","$38,800.00","$47,200.00","$91,600.00","$120,000.00"

### One-to-One dan One-to-Many

In [132]:
unik = (pd.merge(st, wil, how='inner', on='School Name').sort_values(by = 'School Name').drop_duplicates())
pd.merge(st, wil, how='inner', on='School Name').sort_values(by = 'School Name').drop_duplicates()

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
169,Appalachian State University,State,"$40,400.00","$69,100.00",Southern
58,Arizona State University (ASU),State,"$47,400.00","$84,100.00",Western
184,Arkansas State University (ASU),State,"$38,700.00","$63,300.00",Southern
48,Auburn University,State,"$45,400.00","$84,700.00",Southern
189,Austin Peay State University,State,"$37,700.00","$59,200.00",Southern
...,...,...,...,...,...
117,Wayne State University,State,"$42,800.00","$76,100.00",Midwestern
107,West Virginia University (WVU),State,"$43,100.00","$78,100.00",Southern
175,Western Carolina University,State,"$36,900.00","$66,600.00",Southern
131,Western Michigan University (WMU),State,"$42,300.00","$73,800.00",Midwestern
122,Western Washington University,State,"$42,700.00","$75,400.00",Western

In [126]:
wil['School Name'].is_unique

False

In [128]:
st['School Name'].is_unique

True

In [131]:
unik['School Name'].is_unique

True