<a href="https://colab.research.google.com/github/KevinCandra9999/colab-3/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.__version__

'1.5.3'

### 1

In [2]:
pd.read_csv('https://thinkjubilee.com/sekolah.csv')

                Provinsi     SD    SMP    SMA     PT
0                   ACEH  99.85  98.09  82.15  34.28
1         SUMATERA UTARA  99.49  96.60  76.76  26.80
2         SUMATERA BARAT  99.50  96.29  82.86  35.45
3                   RIAU  98.98  94.73  76.52  27.28
4                  JAMBI  99.59  95.89  71.54  24.12
5       SUMATERA SELATAN  99.63  94.01  69.05  19.17
6               BENGKULU  99.80  97.20  79.07  29.90
7                LAMPUNG  99.78  94.76  70.03  20.96
8   KEP. BANGKA BELITUNG  99.64  92.41  66.99  14.99
9              KEP. RIAU  99.32  99.08  82.80  19.13
10           DKI JAKARTA  99.67  97.64  71.50  24.60
11            JAWA BARAT  99.51  93.77  66.62  21.50
12           JAWA TENGAH  99.62  95.48  68.48  22.13
13         DI YOGYAKARTA  99.87  99.63  87.61  51.33
14            JAWA TIMUR  99.57  96.77  71.51  23.34
15                BANTEN  99.31  95.67  67.77  21.33
16                  BALI  99.44  97.72  82.16  26.56
17   NUSA TENGGARA BARAT  99.43  97.69  76.61  28.52
18   NUSA TENGGARA TIMUR  98.27  94.76  74.65  27.80
19      KALIMANTAN BARAT  98.44  92.51  67.53  25.80
20     KALIMANTAN TENGAH  99.50  93.37  66.62  24.15
21    KALIMANTAN SELATAN  99.55  92.33  68.30  23.53
22      KALIMANTAN TIMUR  99.67  98.79  81.32  30.04
23      KALIMANTAN UTARA  98.34  96.04  75.12  20.72
24        SULAWESI UTARA  99.37  94.91  73.04  24.22
25       SULAWESI TENGAH  98.15  92.41  74.87  26.31
26      SULAWESI SELATAN  99.16  93.09  70.60  32.16
27     SULAWESI TENGGARA  99.32  94.08  72.94  30.03
28             GORONTALO  98.76  91.23  69.86  29.21
29        SULAWESI BARAT  98.10  89.88  68.03  23.49
30                MALUKU  99.72  96.86  79.08  38.20
31          MALUKU UTARA  99.19  97.24  76.06  32.10
32           PAPUA BARAT  97.27  96.92  80.60  31.92
33                 PAPUA  81.80  79.09  63.35  24.57

In [3]:
pendidikan = pd.read_csv('https://thinkjubilee.com/sekolah.csv')

In [4]:
type(pendidikan)

pandas.core.frame.DataFrame

In [5]:
nama = ['Joni','Jono','Jana','Jini','Junu']
usia = [20,22,24,26,28]
menikah = [False,True,True,False,True]

In [6]:
df = pd.DataFrame ({'nama' : nama, 'usia' : usia, 'menikah' : menikah})

In [7]:
df

   nama  usia  menikah
0  Joni    20    False
1  Jono    22     True
2  Jana    24     True
3  Jini    26    False
4  Junu    28     True

In [8]:
df.drop('nama',axis=1)

   usia  menikah
0    20    False
1    22     True
2    24     True
3    26    False
4    28     True

In [9]:
df.sample(3)

   nama  usia  menikah
3  Jini    26    False
1  Jono    22     True
4  Junu    28     True

In [10]:
df.axes

[RangeIndex(start=0, stop=5, step=1),
 Index(['nama', 'usia', 'menikah'], dtype='object')]

In [11]:
df.axes[0]

RangeIndex(start=0, stop=5, step=1)

In [12]:
df.axes[1]

Index(['nama', 'usia', 'menikah'], dtype='object')

In [13]:
df.axes[1][2]

'menikah'

In [14]:
df.index[2]

2

In [15]:
df.columns[2]

'menikah'

In [16]:
df

   nama  usia  menikah
0  Joni    20    False
1  Jono    22     True
2  Jana    24     True
3  Jini    26    False
4  Junu    28     True

In [17]:
df.loc[2]

nama       Jana
usia         24
menikah    True
Name: 2, dtype: object

In [18]:
pd.read_csv('https://thinkjubilee.com/sekolah.csv')

                Provinsi     SD    SMP    SMA     PT
0                   ACEH  99.85  98.09  82.15  34.28
1         SUMATERA UTARA  99.49  96.60  76.76  26.80
2         SUMATERA BARAT  99.50  96.29  82.86  35.45
3                   RIAU  98.98  94.73  76.52  27.28
4                  JAMBI  99.59  95.89  71.54  24.12
5       SUMATERA SELATAN  99.63  94.01  69.05  19.17
6               BENGKULU  99.80  97.20  79.07  29.90
7                LAMPUNG  99.78  94.76  70.03  20.96
8   KEP. BANGKA BELITUNG  99.64  92.41  66.99  14.99
9              KEP. RIAU  99.32  99.08  82.80  19.13
10           DKI JAKARTA  99.67  97.64  71.50  24.60
11            JAWA BARAT  99.51  93.77  66.62  21.50
12           JAWA TENGAH  99.62  95.48  68.48  22.13
13         DI YOGYAKARTA  99.87  99.63  87.61  51.33
14            JAWA TIMUR  99.57  96.77  71.51  23.34
15                BANTEN  99.31  95.67  67.77  21.33
16                  BALI  99.44  97.72  82.16  26.56
17   NUSA TENGGARA BARAT  99.43  97.69  76.61  28.52
18   NUSA TENGGARA TIMUR  98.27  94.76  74.65  27.80
19      KALIMANTAN BARAT  98.44  92.51  67.53  25.80
20     KALIMANTAN TENGAH  99.50  93.37  66.62  24.15
21    KALIMANTAN SELATAN  99.55  92.33  68.30  23.53
22      KALIMANTAN TIMUR  99.67  98.79  81.32  30.04
23      KALIMANTAN UTARA  98.34  96.04  75.12  20.72
24        SULAWESI UTARA  99.37  94.91  73.04  24.22
25       SULAWESI TENGAH  98.15  92.41  74.87  26.31
26      SULAWESI SELATAN  99.16  93.09  70.60  32.16
27     SULAWESI TENGGARA  99.32  94.08  72.94  30.03
28             GORONTALO  98.76  91.23  69.86  29.21
29        SULAWESI BARAT  98.10  89.88  68.03  23.49
30                MALUKU  99.72  96.86  79.08  38.20
31          MALUKU UTARA  99.19  97.24  76.06  32.10
32           PAPUA BARAT  97.27  96.92  80.60  31.92
33                 PAPUA  81.80  79.09  63.35  24.57

In [19]:
DataProvinsi = pd.read_csv('https://thinkjubilee.com/sekolah.csv', index_col='Provinsi')

In [20]:
DataProvinsi.loc['JAMBI']

SD     99.59
SMP    95.89
SMA    71.54
PT     24.12
Name: JAMBI, dtype: float64

In [21]:
DataProvinsi.loc['DKI JAKARTA']['SD']

99.67

In [22]:
DataProvinsi.loc['DKI JAKARTA':'DI YOGYAKARTA']

                  SD    SMP    SMA     PT
Provinsi
DKI JAKARTA    99.67  97.64  71.50  24.60
JAWA BARAT     99.51  93.77  66.62  21.50
JAWA TENGAH    99.62  95.48  68.48  22.13
DI YOGYAKARTA  99.87  99.63  87.61  51.33

In [23]:
DataProvinsi.loc[['DKI JAKARTA','DI YOGYAKARTA'],['SD','SMP']]

                  SD    SMP
Provinsi
DKI JAKARTA    99.67  97.64
DI YOGYAKARTA  99.87  99.63

### 2

In [24]:
data_url = 'http://thinkjubilee.com/bola.csv'
pemainbola = pd.read_csv(data_url)

In [25]:
pemainbola[pemainbola.market_value	>= 60]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
96,Eden Hazard,Chelsea,26,LW,1,75.0,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.0,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Manchester+City,29,CF,1,65.0,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
267,Paul Pogba,Manchester+United,24,CM,2,75.0,7435,8.0,19.50%,115,2,France,0,2,12,1,1
381,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0

In [26]:
pemainbola.market_value	>= 60

0       True
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Name: market_value, Length: 465, dtype: bool

In [27]:
pemainbola[pemainbola.market_value	== 65].shape

(3, 17)

In [28]:
pemainbola.nationality.unique()

array(['Chile', 'Germany', 'Czech Republic', 'England', 'France', 'Spain',
       'Nigeria', 'Switzerland', 'Wales', 'Brazil', 'Egypt', 'Argentina',
       'Colombia', 'Bosnia', 'Norway', 'Poland', 'Scotland', 'Congo DR',
       'Ireland', 'Netherlands', 'Australia', "Cote d'Ivoire", 'Finland',
       'Cameroon', 'Austria', 'Israel', 'Northern Ireland', 'Canada',
       'Belgium', 'Iceland', 'Serbia', 'Portugal', 'Ghana', 'South Korea',
       'Mali', 'Senegal', 'Curacao', 'Denmark', 'Slovenia',
       'Trinidad and Tobago', 'Bermuda', 'Benin', 'Algeria', 'Jamaica',
       'Japan', 'Tunisia', 'Croatia', 'Estonia', 'Ecuador', 'Armenia',
       'Italy', 'Sweden', 'United States', 'Morocco', 'The Gambia',
       'Kenya', 'Greece', 'Uruguay', 'Romania', 'Venezuela',
       'New Zealand'], dtype=object)

In [29]:
pemainbola.nationality.unique().size

61

In [30]:
pemainbola.nationality.isin(['England', 'South Korea', 'Italy'])

0      False
1      False
2      False
3       True
4      False
       ...
460    False
461    False
462     True
463     True
464    False
Name: nationality, Length: 465, dtype: bool

In [31]:
pemainbola[pemainbola.nationality.isin(['England', 'South Korea', 'Italy'])]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
12,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
13,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
14,Jack Wilshere,Arsenal,25,CM,2,18.0,1759,5.5,0.00%,61,1,England,0,3,1,1,0
18,Kieran Gibbs,Arsenal,27,LB,3,10.0,489,5.0,0.50%,45,1,England,0,3,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,Andy Carroll,West+Ham,28,CF,1,10.0,1212,6.0,0.40%,69,1,England,0,4,20,0,0
455,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
458,Angelo Ogbonna,West+Ham,29,CB,3,9.0,247,4.5,1.10%,45,2,Italy,0,4,20,0,0
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1

In [32]:
pemainbola[pemainbola.market_value.between(65,75)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
96,Eden Hazard,Chelsea,26,LW,1,75.0,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.0,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Manchester+City,29,CF,1,65.0,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
267,Paul Pogba,Manchester+United,24,CM,2,75.0,7435,8.0,19.50%,115,2,France,0,2,12,1,1

In [33]:
pemainbola[pemainbola.market_value.between(65,75, inclusive=False)]

<ipython-input-33-47f6d8980ea2>:1: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  pemainbola[pemainbola.market_value.between(65,75, inclusive=False)]

Empty DataFrame
Columns: [name, club, age, position, position_cat, market_value, page_views, fpl_value, fpl_sel, fpl_points, region, nationality, new_foreign, age_cat, club_id, big_club, new_signing]
Index: []

In [34]:
pemainbola[pemainbola.age >= 25].shape

(335, 17)

In [35]:
pemainbola[pemainbola.age.le(25)].shape

(172, 17)

In [36]:
pemainbola[pemainbola.age.lt(25)].shape

(130, 17)

In [37]:
pemainbola[pemainbola.age.gt(25)].shape

(293, 17)

In [38]:
pemainbola[pemainbola.age.ge(25)].shape

(335, 17)

In [39]:
pemainbola[pemainbola.age.eq(25)].shape

(42, 17)

In [40]:
pemainbola[(pemainbola.market_value.gt(30)) &
            (pemainbola.nationality == 'England')]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
246,Raheem Sterling,Manchester+City,22,LW,1,45.0,2074,8.0,3.80%,149,1,England,0,2,11,1,0
256,John Stones,Manchester+City,23,CB,3,35.0,1078,5.5,2.30%,59,1,England,0,2,11,1,1
380,Dele Alli,Tottenham,21,CM,2,45.0,4626,9.5,38.60%,225,1,England,0,1,17,1,0
381,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0

In [41]:
pemainbola[(pemainbola.age.lt(30)) &
            (pemainbola.club == 'Arsenal') &
             (pemainbola.market_value.gt(30))]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
10,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
11,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
15,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
31,Alexandre Lacazette,Arsenal,26,CF,1,40.0,1183,10.5,26.50%,0,2,France,1,3,1,1,0

In [47]:
usia = pemainbola.age.lt(30)
klub = pemainbola.club == 'Arsenal'
market = pemainbola.market_value.gt(30)
pemainbola[(usia) &
          (klub) &
          (market)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
10,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
11,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
15,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
31,Alexandre Lacazette,Arsenal,26,CF,1,40.0,1183,10.5,26.50%,0,2,France,1,3,1,1,0
96,Eden Hazard,Arsenal,26,LW,1,75.0,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
97,Diego Costa,Arsenal,28,CF,1,50.0,4454,10.0,3.00%,196,2,Spain,0,4,5,1,0
102,Thibaut Courtois,Arsenal,25,GK,4,40.0,1260,5.5,18.50%,141,2,Belgium,0,3,5,1,0
105,Willian,Arsenal,28,RW,1,32.0,1165,7.0,9.00%,114,3,Brazil,0,4,5,1,0
107,Nemanja Matic,Arsenal,28,DM,2,35.0,892,5.0,5.00%,105,2,Serbia,0,4,5,1,0
108,N%27Golo Kante,Arsenal,26,DM,2,50.0,4042,5.0,13.80%,83,2,France,0,3,5,1,1
217,Roberto Firmino,Arsenal,25,SS,1,38.0,2196,8.5,20.30%,180,3,Brazil,0,3,10,1,0
218,Philippe Coutinho,Arsenal,25,AM,1,45.0,2958,9.0,30.80%,171,3,Brazil,0,3,10,1,0
219,Sadio Mane,Arsenal,25,LW,1,40.0,3219,9.5,5.30%,156,4,Senegal,0,3,10,1,1
241,Mohamed Salah,Arsenal,25,RW,1,35.0,1117,9.0,12.40%,0,4,Egypt,1,3,10,1,0
244,Kevin De Bruyne,Arsenal,26,AM,1,65.0,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Arsenal,29,CF,1,65.0,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
246,Raheem Sterling,Arsenal,22,LW,1,45.0,2074,8.0,3.80%,149,1,England,0,2,11,1,0
249,Leroy Sane,Arsenal,21,LW,1,35.0,2302,8.5,8.80%,105,2,Germany,0,1,11,1,1
256,John Stones,Arsenal,23,CB,3,35.0,1078,5.5,2.30%,59,1,England,0,2,11,1,1
263,Bernardo Silva,Arsenal,22,RW,1,40.0,1098,8.0,4.60%,0,2,Portugal,1,2,11,1,0
264,Romelu Lukaku,Arsenal,24,CF,1,50.0,3727,11.5,45.00%,221,2,Belgium,0,2,12,1,0
265,David de Gea,Arsenal,26,GK,4,40.0,2126,5.5,26.10%,136,2,Spain,0,3,12,1,0
267,Paul Pogba,Arsenal,24,CM,2,75.0,7435,8.0,19.50%,115,2,France,0,2,12,1,1
275,Henrikh Mkhitaryan,Arsenal,28,AM,1,35.0,3312,8.0,4.50%,73,4,Armenia,0,4,12,1,1
380,Dele Alli,Arsenal,21,CM,2,45.0,4626,9.5,38.60%,225,1,England,0,1,17,1,0
381,Harry Kane,Arsenal,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0
382,Christian Eriksen,Arsenal,25,AM,1,40.0,1130,9.5,12.00%,218,2,Denmark,0,3,17,1,0
386,Toby Alderweireld,Arsenal,28,CB,3,35.0,756,6.0,13.30%,120,2,Belgium,0,4,17,1,0

In [50]:
usia = pemainbola.age.lt(30)
klub = pemainbola.club == 'Arsenal'
market = pemainbola.market_value.gt(30)
pemainbola[(usia) |
          (klub) |
          (market)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Edimilson Fernandes,Arsenal,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
461,Arthur Masuaku,Arsenal,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,Arsenal,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,Arsenal,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1
464,Diafra Sakho,Arsenal,27,CF,1,10.0,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

In [68]:
usia = pemainbola.age.lt(30)
klub = pemainbola.club == 'Arsenal'
market = pemainbola.market_value.gt(30)
pemainbola.loc[(usia) & (klub) & (market), ['name','age','club','market_value','nationality']]

                    name  age     club  market_value  nationality
0         Alexis Sanchez   28  Arsenal          65.0        Chile
1             Mesut Ozil   28  Arsenal          50.0      Germany
10          Granit Xhaka   24  Arsenal          35.0  Switzerland
11          Granit Xhaka   24  Arsenal          35.0  Switzerland
15          Aaron Ramsey   26  Arsenal          35.0        Wales
31   Alexandre Lacazette   26  Arsenal          40.0       France
96           Eden Hazard   26  Arsenal          75.0      Belgium
97           Diego Costa   28  Arsenal          50.0        Spain
102     Thibaut Courtois   25  Arsenal          40.0      Belgium
105              Willian   28  Arsenal          32.0       Brazil
107        Nemanja Matic   28  Arsenal          35.0       Serbia
108       N%27Golo Kante   26  Arsenal          50.0       France
217      Roberto Firmino   25  Arsenal          38.0       Brazil
218    Philippe Coutinho   25  Arsenal          45.0       Brazil
219           Sadio Mane   25  Arsenal          40.0      Senegal
241        Mohamed Salah   25  Arsenal          35.0        Egypt
244      Kevin De Bruyne   26  Arsenal          65.0      Belgium
245        Sergio Aguero   29  Arsenal          65.0    Argentina
246      Raheem Sterling   22  Arsenal          45.0      England
249           Leroy Sane   21  Arsenal          35.0      Germany
256          John Stones   23  Arsenal          35.0      England
263       Bernardo Silva   22  Arsenal          40.0     Portugal
264        Romelu Lukaku   24  Arsenal          50.0      Belgium
265         David de Gea   26  Arsenal          40.0        Spain
267           Paul Pogba   24  Arsenal          75.0       France
275   Henrikh Mkhitaryan   28  Arsenal          35.0      Armenia
380            Dele Alli   21  Arsenal          45.0      England
381           Harry Kane   23  Arsenal          60.0      England
382    Christian Eriksen   25  Arsenal          40.0      Denmark
386    Toby Alderweireld   28  Arsenal          35.0      Belgium